### ISSUE TITLE
Walking after switching tabs

### ISSUE THREAD

**Issue by LeweC** [8BitJonny/JsGame#1]
The character keeps walking after you press a direction key and simultaneously switch to a different tab. He stops walking again after the button is pressed again.

**Comment by 8BitJonny** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stop die Bewegung wenn der Browser Tab Fokus verliert](https://trello.com/c/cmEUunzU/24-stop-die-bewegung-wenn-der-browser-tab-fokus-verliert)
